language: java
jdk:
  - openjdk11
branches:
  only:
    - main

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r reservation-service *
  - mkdir -p deploy
  - mv reservation-service.zip deploy/reservation-service.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: reservation-service-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      all_branches: true # error: Skipping a deployment with the s3 provider because this branch is not permitted: main

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: reservation-service
    key: reservation-service.zip
    bundle-type: zip
    application: reservation-service
    deployment-group: reservation-service-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - xbox2537@gmail.com